### ISSUE TITLE
Broken Brazilian Portuguese (Português) learnyounode verify submission 

### ISSUE THREAD

**Issue by isRuslan** [workshopper/learnyounode#229]
Just accidentally discovered an error on `verify` *any exercise* when `pt-br` language selected.
Here is full terminal output:

```sh
➤ learnyounode -v                                                                                                                                                                 
learnyounode@2.4.0

➤ learnyounode -l pt-br # and choose "hello world" exercise

➤ learnyounode verify 01.js                                                                                                                  

?exercises.HELLO WORLD.compare.title || common.exercise.compare.title?


/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/comparestdout.js:19
  return new Array(sz + 1).join(ch)
         ^
RangeError: Invalid array length
    at repeat (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/comparestdout.js:19:10)
    at center (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/comparestdout.js:25:13)
    at Exercise.transform (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/comparestdout.js:57:40)
    at Transform._read (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.emit (events.js:95:17)
➤ cat $_                                                                                                                                                                         
console.log("HELLO WORLD")
```

It looks like that the problem is the lack of `pt-br.json` in [rvagg/workshopper-exercise/i18n](https://github.com/rvagg/workshopper-exercise/tree/master/i18n) directory, played with that:

```sh
# copy en.json to pt-br.json for `worshopper-exercise` in `learnyounode` path
➤ cp /usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/i18n/{en.json,pt-br.json}                                                                           
➤ learnyounode verify 01.js                                                                                                                    

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   "HELLO WORLD"                       ==    "HELLO WORLD"
   ""                                  ==    ""

────────────────────────────────────────────────────────────────────────────────

✓ Submission results match expected

# SUCESSO

Sua solução para OLÁ, MUNDO foi aprovada!

Aqui está a solução original, caso você deseje comparar:

────────────────────────────────────────────────────────────────────────────────
    console.log("HELLO WORLD")

────────────────────────────────────────────────────────────────────────────────

Você tem 7 desafios restantes.
Digite 'learnyounode' para mostrar o menu.
```

Seems like Brazilian Portuguese collaborators just need to add `pt-br.json` config to [rvagg/workshopper-exercise/i18n](https://github.com/rvagg/workshopper-exercise/tree/master/i18n) to fix this.

**Comment by thiagosantos** [comment]
@isRuslan is already fixed! https://github.com/workshopper/workshopper-exercise/commit/ecd5ccf6c2811e2e328097246c37a90e78cd45bc

**Comment by isRuslan** [comment]
True, closing this issue.
Thanks @thiagosantos!

**Comment by kresmachine** [comment]
same problem still happening on tr(turkish) language.
