### ISSUE TITLE
Could not get HTTP FILE SERVER solution to complete

### ISSUE THREAD

**Issue by Shawful** [workshopper/learnyounode#313]
Hello,

I could not get the HTTP FILE SERVER exercise to pass, even after copying the solution from github. 

Instead, I am returned the following error:

Error from either "learnyounode run fileserver.js" or "learnyounode verify fileserver.js"
fs.js:429
  binding.open(pathModule._makeLong(path),
          ^
TypeError: path must be a string
    at Object.fs.open (fs.js:429:11)
    at ReadStream.open (fs.js:1508:6)
    at new ReadStream (fs.js:1495:10)
    at Object.fs.createReadStream (fs.js:1449:10)
    at Server.<anonymous> (/home/shawn/git/tutorials/learnyounode/fileserver/fileserver.js:7:4)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2112:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1970:22)
    at TCP.onread (net.js:527:27)
✗ Error connecting to http://localhost:58071: read ECONNRESET

I have tried applying the .toString() method to each of the command line argument objects, but that did not resolve the issue.

Any ideas?

**Comment by Shawful** [comment]
nvmd. I had selected a different exercise after typing "learnyounode" and that changed the verification guidelines ran by "learnyounode verify [programName].js"
