### ISSUE TITLE
Learnyounode installs and runs, but errors when I choose lesson

### ISSUE THREAD

**Issue by isabellaorgan** [workshopper/learnyounode#374]
Installed learnyounode fine:
```
/Users/isabellaorgan/.node/bin/learnyounode -> /Users/isabellaorgan/.node/lib/node_modules/learnyounode/bin/learnyounode
learnyounode@3.0.0 /Users/isabellaorgan/.node/lib/node_modules/learnyounode
├── duplexer@0.1.1
├── after@0.8.1
├── rimraf@2.2.8
├── through@2.3.8
├── boganipsum@0.1.0
├── combined-stream@0.0.7 (delayed-stream@0.0.5)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── workshopper-wrappedexec@0.1.2 (xtend@2.1.2)
├── colors-tmpl@1.0.0 (colors@1.0.3)
├── bl@0.9.4 (readable-stream@1.0.33)
├── through2@0.6.5 (xtend@4.0.1, readable-stream@1.0.33)
├── concat-stream@1.4.10 (inherits@2.0.1, typedarray@0.0.6, readable-stream@1.1.13)
├── through2-map@1.4.0 (xtend@3.0.0, through2@0.5.1, terminus@1.0.12)
├── hyperquest@1.0.1 (duplexer2@0.0.2)
├── workshopper-exercise@2.5.3 (tuple-stream@0.0.2, split@0.3.3, visualwidth@0.0.1, chalk@0.4.0, xtend@2.1.2, through2@0.4.2, i18n-core@1.3.3)
└── workshopper-adventure@4.2.1 (xtend@3.0.0, visualwidth@0.1.0, split@1.0.0, chalk@0.4.0, string-to-stream@1.0.1, mkdirp@0.3.5, colors-tmpl@0.1.1, i18n-core@2.1.1, through2@2.0.0, concat-stream@1.5.1, simple-terminal-menu@1.1.1, rimraf@2.4.3, @leichtgewicht/msee@0.3.0, commandico@2.0.0)
```

And then it opens fine, but when I select any lesson and hit Enter, I get the following error message:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'ansicolors'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/isabellaorgan/.node/lib/node_modules/learnyounode/node_modules/workshopper-adventure/node_modules/@leichtgewicht/msee/lib/syntaxColor.js:1:76)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by martinheidegger** [comment]
Thank you for reporting this, there seems to be a slight difference in npm that makes it work for me. I need another hour to publish a fix. Sorry for the inconvenience

**Comment by martinheidegger** [comment]
I just published the latest version, it should work now.

**Comment by isabellaorgan** [comment]
Cool, that appears to have worked after an update. Thanks!
