### ISSUE TITLE
Can't arrow up and down

### ISSUE THREAD

**Issue by revxx14** [workshopper/learnyounode#399]
This works on one of my 64-bit Windows 10 machines, but not on another. I run learnyounode and it opens the interface, bur arrowing up and down does nothing. I can hit enter to load the first one, but I can't select the second, third, fourth, etc.

Tried running the prompt as admin, as suggested in #344, made no difference. Also tried it in git bash and PowerShell.

Any ideas what could be happening?

**Comment by eveningkid** [comment]
Same problem here using that same configuration too. Worked fine using 8.1...

**Comment by martinheidegger** [comment]
What node.js version do you have installed?

**Comment by revxx14** [comment]
I believe 5.4.1

**Comment by martinheidegger** [comment]
I know that this is asking a lot but could you check other 5.x versions to see if it doesn't work on all of them?

**Comment by joeparis** [comment]
For what it's worth I experienced the same problem as @revxx14 (navigation works on one machine but not another. Using nodist I tested with 5.8.0 and 5.6.0 and saw the same behavior. Changing to 4.3.0 caused the arrow keys to start responding again.

**Comment by todef96** [comment]
This looks to be a workshopper issue? I have the same problem on win64bit with node 5.0.0. I managed to crash it by typing random keys (which let you type below the menu). You can still press enter to enter the exercises.

Output from crash (this appears to be from the input key strokes however):

`events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: write after end
    at writeAfterEnd (C:\Users\admin\AppData\Roaming\npm\node_modules\learnyouno
de\node_modules\extended-terminal-menu\node_modules\readable-stream\lib\_stream_
writable.js:144:12)
    at DestroyableTransform.Writable.write (C:\Users\admin\AppData\Roaming\npm\n
ode_modules\learnyounode\node_modules\extended-terminal-menu\node_modules\readab
le-stream\lib\_stream_writable.js:192:5)
    at Charm.ondata (stream.js:31:26)
    at emitOne (events.js:82:20)
    at Charm.emit (events.js:169:7)
    at Charm.write (C:\Users\admin\AppData\Roaming\npm\node_modules\learnyounode
\node_modules\charm_inheritance-fix\index.js:96:10)
    at Charm.reset (C:\Users\admin\AppData\Roaming\npm\node_modules\learnyounode
\node_modules\charm_inheritance-fix\index.js:114:10)
    at Menu.ondata [as _ondata] (C:\Users\admin\AppData\Roaming\npm\node_modules
\learnyounode\node_modules\extended-terminal-menu\index.js:208:24)
    at DestroyableTransform._transform (C:\Users\admin\AppData\Roaming\npm\node_
modules\learnyounode\node_modules\extended-terminal-menu\index.js:50:18)
    at DestroyableTransform.Transform._read (C:\Users\admin\AppData\Roaming\npm\
node_modules\learnyounode\node_modules\extended-terminal-menu\node_modules\reada
ble-stream\lib\_stream_transform.js:184:10)`

**Comment by martinheidegger** [comment]
@todef96 Node 5.0.0 is known to not work. They fixed a bug in 5.2.0 if I remember properly. _(Note: We need a module that knows which versions of Node dont work ...)_
