### ISSUE TITLE
Error: Cannot find module after Installation

### ISSUE THREAD

**Issue by ArchitW** [workshopper/learnyounode#407]
`C:\wamp\www\tuts\node>node learnyournode
module.js:328
    throw err;
    ^

Error: Cannot find module 'C:\wamp\www\tuts\node\learnyournode'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3`

**Comment by jmalk** [comment]
If I've understood correctly you have run the command `node learnyournode`. There are two possible problems:

* The module is called learnyounode not learnyou**r**node.
* The module can be run by simply typing `learnyounode` once it is installed globally.

I don't use Windows, so I might be way off, but I hope it helps!

**Comment by ArchitW** [comment]
`C:\wamp\www\tuts\node>node` `learnyournode`
module.js:328
    throw err;
    ^

Error: Cannot find module 'C:\wamp\www\tuts\node\learnyournode'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

@jmalk still same issue

**Comment by Subway19** [comment]
I think some of the modules are not installed or updated. Use the `npm update` and `npm install` command in your directory.  Is `node_modules`  folder  in your directory?

**Comment by Subway19** [comment]
When you do `node learnyournode.js` - it tries to run a file that doesn't exist, which is why you're getting an error.

**Comment by jmalk** [comment]
Unless you've installed it under a different name, this module is called learnyounode.

The output you've pasted says learnyournode with an "r", and I think this may be why node is unable to find the module.

**Comment by karanpepi** [comment]
When you are cloning or installing project on your machine you need to go to the folder where there is package.json file and then run `npm install `. Hope this works for you

**Comment by AnshulMalik** [comment]
@ArchitW What I can understand from this issue is:
- You have installed `learnyounode` package by running `sudo npm install -g learnyounode`

Now, you are trying to run it, and you are getting this  error.

If it is so, you just need to run `learnyounode` in terminal instead of `node learnyounode` or `node learnyournode`

**Comment by ptarwireyi** [comment]
I had the same problem in windows 10, when i tried running `learnyounode` _and_ `javascripting` in _git bash_.

```
`$ node learnyounode
module.js:487
    throw err;
    ^

Error: Cannot find module 'C:\Users\....\learnyounode'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

# All worked fine when i ran the packages in the windows `# **Command Prompt**`
