### ISSUE TITLE
［osx］Connection ERR occur while verify with official code

### ISSUE THREAD

**Issue by joseeph** [workshopper/learnyounode#422]
stuck on the TIME SERVER !

Jo:learnyounode Joseph$ learnyounode verify program.js 
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '17717'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/Users/Joseph/Documents/nodeSchool/learnyounode/program.js:3:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   ""                                  !=    "2016-03-14 11:45"                 
                                       !=    ""                                 

────────────────────────────────────────────────────────────────────────────────

  ✗  Error connecting to localhost:17717: connect ECONNREFUSED  
  127.0.0.1:17717  
   
  ✗  Submission results did not match expected!  
   
       
     # FAIL  
     Your solution to TIME SERVER didn't pass. Try again!

**Comment by irliao** [comment]
Did you use the first argument as the port number or did you hardcode a value in server.listen()? 

I had the same issue as you but turned out I was supposed to do server.listen(process.argv[2]) instead of server.listen(8000) that came from the instructions.
