### ISSUE TITLE
Make it Modular - Type Error 

### ISSUE THREAD

**Issue by cbuchert** [workshopper/learnyounode#439]
When I go to test my modules (`$ earnyounode verify ex6.js`), I get the following message:

```
Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
   "LICENCE.md"                        ==    "LICENCE.md"                       
   "README.md"                         ==    "README.md"                        
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:188
    processors[i].call(self, mode, function (err, pass) {
                 ^

TypeError: Cannot read property 'call' of undefined
    at next (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:188:18)
    at /home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:195:7
    at callback (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:26:15)
    at modFileError (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:31:5)
    at /home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:109:18
    at /home/ubuntu/workspace/dev/ex6-module.js:11:5
    at Array.forEach (native)
    at /home/ubuntu/workspace/dev/ex6-module.js:7:9
    at FSReqWrap.oncomplete (fs.js:82:15)
```

The two files I wrote are as follows:

ex6.js

``` javascript
var dir = require("./ex6-module.js");

dir(process.argv[2], process.argv[3], function(file) {
    console.log(file);
});
```

ex6-module.js

``` javascript
module.exports = function(path, extension, callback) {
    var fs = require("fs");

    fs.readdir(path, function(err, files) {
        if (err) return callback(err);

        files.forEach(function(file) {
            var fileExtension = file.split('.')[1];

            if (fileExtension === extension) {
                callback(file);
            }
        });
    });
};
```

Ideas?

**Comment by jhuynh85** [comment]
I'm also getting the same error:

```
$ learnyounode verify program.js

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
   "LICENCE.md"                        ==    "LICENCE.md"                       
   "README.md"                         ==    "README.md"                        
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:188
    processors[i].call(self, mode, function (err, pass) {
                 ^

TypeError: Cannot read property 'call' of undefined
    at next (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:188:18)
    at /home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:195:7
    at callback (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:26:15)
    at modFileError (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:31:5)
    at /home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:119:18
    at /home/ubuntu/workspace/filtered-module.js:13:17
    at FSReqWrap.oncomplete (fs.js:82:15)
```
For reference, my files are:

 **program.js**
```javascript
var fm = require('./filtered-module.js');

fm(process.argv[2], process.argv[3], function(err, data){
   if (!err){
       console.log(data);
   } else {
       console.log("ERROR!");
   }
});
```
**filtered-module.js**
```javascript
var fs = require('fs');
var path = require('path');

module.exports = function(pa, ext, callback){
    var exten = "."+ext;
    fs.readdir(pa, function(err, fileStr){
        if (err){
            return callback(err);
        }
        
        for (var i=0; i<fileStr.length;i++){
            if (path.extname(fileStr[i])==exten){
                callback(null,fileStr[i]);
            }
        }
    });
};
```

Any help would be appreciated

**Comment by jhuynh85** [comment]
Found the solution [here](https://github.com/nodeschool/discussions/issues/1606).
