### ISSUE TITLE
Struggling to get code running 

### ISSUE THREAD

**Issue by stevywil** [workshopper/learnyounode#475]
I'm completely new to using node.js and pretty much coding in general so I'm not sure if this is just me being stupid but any help to get me running would be appreciated.

* node version: v6.6.0
* npm version:  v3.10.3

### Error output
```
/Users/stevywil/Documents/Node/learnyounode/helloWorld.js:1
(function (exports, require, module, __filename, __dirname) { console.log(“HELLO WORLD”)
                                                                          ^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   ""                                  !=    "HELLO WORLD"                      
                                       !=    ""                                 

────────────────────────────────────────────────────────────────────────────────

  ✗  Submission results did not match expected! 
```

### My Code
```js
console.log(“HELLO WORLD”)
```

**Comment by martinheidegger** [comment]
It seems like you use an editor that fixes quotes. In JavaScript, like in most programming languages, you need to use it like explained here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String

**Comment by stevywil** [comment]
Thank you! I've managed to sort it by using Nano.
