### ISSUE TITLE
Make it modular

### ISSUE THREAD

**Issue by hanhdt** [workshopper/learnyounode#505]
I'm taking the Make It Modular challenge.

This is my module filtered_ls.js

```
var fs = require('fs');
var path = require('path');

// Export function for reading files in the directory with specific ext.
module.exports = function(dirname, ext, callback) {
    fs.readdir(dirname, function(err, files) {
        if (err) {
            return callback(err);
        }
        for (var index = 0; index < files.length; index++) {
            if (path.extname(files[index]).split('.').pop() === ext) {
                callback(null, files[index]);
            }
        }
    });
}
```

Main program file:

```
var filteredLS = require('./filtered_ls.js');

filteredLS(process.argv[2], process.argv[3], printResult);

function printResult(err, data) {
    if (err) return console.error(err);
    console.log(data);
}
```

I got passed all steps but it was shown up:

# LEARN YOU THE NODE.JS FOR MUCH WIN!

## MAKE IT MODULAR (Exercise 6 of 13)

Your submission results compared to the expected:

   ```
              ACTUAL                                 EXPECTED
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"
   "LICENCE.md"                        ==    "LICENCE.md"
   "README.md"                         ==    "README.md"
   ""                                  ==    ""

────────────────────────────────────────────────────────────────────────────────
 ✓

 Submission results match expected

 ✓

 Additional module file exports a single function

 ✓

 Additional module file exports a function that takes 3 arguments

 ✓

 Additional module file handles errors properly

 ✓

 Additional module file handles callback argument

/usr/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:188
    processors[i].call(self, mode, function (err, pass) {
                 ^

TypeError: Cannot read property 'call' of undefined
    at next (/usr/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:188:18)
    at /usr/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:195:7
    at callback (/usr/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:26:15)
    at modFileError (/usr/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:31:5)
    at /usr/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:130:18
    at /home/hanh/aromajoin/Nodejs/filtered-ls-module/filtered_ls.js:12:17
    at FSReqWrap.oncomplete (fs.js:82:15)



```

Where have I got wrongs?

Thank you.

**Comment by iv4zbc** [comment]
// Export function for reading files in the directory with specific ext.
module.exports = function(dirname, ext, callback) {
...
**// You need to declare an array of responses**
for (var index = 0; index < files.length; index++) {
            if (path.extname(files[index]).split('.').pop() === ext) {
                **// push element to the array of responses**
            }
        }
**return callback(null, files[index]);**
...

**Comment by iv4zbc** [comment]
return callback(null, arrayOfResponses);

**Comment by hanhdt** [comment]
Yes, I got it. 

Thanks you.
