### ISSUE TITLE
Error when trying to access exercise 6 - Object has no method repeat

### ISSUE THREAD

**Issue by vitroz** [workshopper/learnyounode#520]
I've come across this issue today, all the other exercises work fine. 
When I select exercise 6 I get get following message:

`TypeError: Object   has no method 'repeat'
    at processToken (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-adventure/node_modules/msee/lib/msee.js:266:35)
    at processToken (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-adventure/node_modules/msee/lib/msee.js:246:28)
    at Object.exports.parse (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-adventure/node_modules/msee/lib/msee.js:363:24)
    at module.exports (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-adventure/lib/msee.js:20:15)
    at DestroyableTransform._flush (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-adventure/lib/mseePipe.js:12:15)
    at DestroyableTransform.<anonymous> (/usr/local/lib/node_modules/learnyounode/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.EventEmitter.emit (events.js:92:17)
    at prefinish (/usr/local/lib/node_modules/learnyounode/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:501:12)
    at finishMaybe (/usr/local/lib/node_modules/learnyounode/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:513:7)
`

**Comment by AnshulMalik** [comment]
Well, that's strange.

Are you still facing this issue with latest version of learnyounode? If yes, which node and npm version are you using?

**Comment by shanmukhateja** [comment]
This issue can be marked as closed as it seems to have been resolved. Feel free to reopen the issue if you have something to contribute to it.
