### ISSUE TITLE
Makeitmodular verify gives an error despite running correctly

### ISSUE THREAD

**Issue by Nunoestrada** [workshopper/learnyounode#522]
When I run my exercise script it gives the correct output.
```
$ learnyounode run makeitmodular.js 
CHANGELOG.md
LICENCE.md
README.md
```
But if I run the verify command I get an error in the verification code:
```
$ learnyounode verify

# LEARN YOU THE NODE.JS FOR MUCH WIN!

## MAKE IT MODULAR (Exercise 6 of 13)

Could not verify: TypeError: Cannot read property 'toString' of undefined
    at Exercise.setup (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/filecheck.js:8:21)
    at next (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:145:15)
    at Exercise.setup (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:151:5)
    at Exercise.runVerify (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:158:8)
    at Exercise.verify (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:173:13)
    at WA.executeExercise (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-adventure/index.js:425:16)
    at WA.process (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-adventure/index.js:317:17)
    at WA.verify (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-adventure/index.js:258:15)
    at Object.exports.handler.exports.handler [as handler] (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-adventure/lib/commands/verify.js:12:21)
    at Object.$ (/usr/local/lib/node_modules/learnyounode/node_modules/commandico/commandico.js:143:15)
```

What is wrong with my exercise code?

Cheers
Nuno

**Comment by Nunoestrada** [comment]
Sorry this was my mistake, I was calling the verify command without parameters
