### ISSUE TITLE
Error installing learnyounode: no compatible version found for javascript-test-reporter

### ISSUE THREAD

**Issue by shivanisanyal** [workshopper/learnyounode#553]
I get the following error when installing learnyounode with command " sudo npm install learnyounode -g"

```
> 48233 error Error: No compatible version found: codeclimate-test-reporter@'github:codeclimate/javascript-test-reporter#97f1ff2cf18cd5f03191d3d53e671c47e954f2fa'
> 48233 error Valid install targets:
> 48233 error ["0.0.1","0.0.2","0.0.3","0.0.4","0.1.0","0.1.1","0.2.0","0.2.1","0.3.0","0.3.1","0.3.2","0.3.3","0.4.0","0.4.1","0.5.0"]
> 48233 error     at installTargetsError (/usr/share/npm/lib/cache.js:719:10)
> 48233 error     at /usr/share/npm/lib/cache.js:638:10
> 48233 error     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
> 48233 error     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
> 48233 error     at Object.oncomplete (fs.js:107:15)
> 48234 error If you need help, you may report this log at:
> 48234 error     <http://github.com/isaacs/npm/issues>
> 48234 error or email it to:
> 48234 error     <npm-@googlegroups.com>
> 48235 error System Linux 3.13.0-24-generic
> 48236 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "learnyounode"
> 48237 error cwd /home/shivani/NODEJS/nodeschool
> 48238 error node -v v0.10.25
> 48239 error npm -v 1.3.10
> 48240 verbose exit [ 1, true ]
```

i tried changing the permissions of the node_modules folder to 777. However it did not work. 
What is the solution for this error?

**Comment by kev6** [comment]
Try updating node and npm.

**Comment by shivanisanyal** [comment]
@kev6 that dint work.. any other possible solution?

**Comment by AnshulMalik** [comment]
Hey @shivanisanyal  can you tell the node and npm version you are using?

**Comment by shivanisanyal** [comment]
@AnshulMalik npm version 1.3.10 and node version 0.10.25

**Comment by AnshulMalik** [comment]
Okay, you should have atleast node v 4.8 and npm v2.0. Can you upgrade them and check again?

**Comment by shivanisanyal** [comment]
@AnshulMalik oh my bad. That totally worked! thanks! :)
PS: sorry for the late response.
