### ISSUE TITLE
404 Not Found: learnyournode@latest

### ISSUE THREAD

**Issue by CraftWorker** [workshopper/learnyounode#592]
I'm unsure of why am I getting a 404 here. OS is ubuntu 16.04.
Here's the info from the terminal:

``
xxxxxxx@xxxxxx-xxxM:~$ sudo npm install learnyournode -g
npm ERR! code E404
npm ERR! 404 Not Found: learnyournode@latest
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxxx-xxxx/.npm/_logs/2017-12-06T09_51_56_157Z-debug.log
---------------------------------------------------------------------------------------------------------------
xxxxxxx@xxxxxx-xxxM:~$ npm ping learnyournode
Ping success: {}
---------------------------------------------------------------------------------------------------------------
Here's the full debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'learnyournode' ]
2 info using npm@5.5.1
3 info using node@v9.2.0
4 verbose config Skipping project config: /home/xxxx-xxxx/.npmrc. (matches userconfig)
5 verbose npm-session 08d90bfde387602e
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 404 https://registry.npmjs.org/learnyournode 1589ms
9 silly fetchPackageMetaData error for learnyournode@latest 404 Not Found: learnyournode@latest
10 verbose stack Error: 404 Not Found: learnyournode@latest
10 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
10 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
10 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
10 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
10 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
10 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
10 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
10 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
10 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
10 verbose stack     at runCallback (timers.js:800:20)
10 verbose stack     at tryOnImmediate (timers.js:762:5)
10 verbose stack     at processImmediate [as _immediateCallback] (timers.js:733:5)
11 verbose cwd /home/xxxx-xxxx
12 verbose Linux 4.10.0-40-generic
13 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "learnyournode"
14 verbose node v9.2.0
15 verbose npm  v5.5.1
16 error code E404
17 error 404 Not Found: learnyournode@latest
18 verbose exit [ 1, true ]
---------------------------------------------------------------------------------------------------------------
I did install nodejs-legacy as instructed but as you can see it's still using node v9 maybe it's getting a 404 because of this?
Just disclaiming that npm and git are installed and updated.

**Comment by CraftWorker** [comment]
Problem fixed by cloning and running npm in the directory.
