### ISSUE TITLE
Problem Verifying Exercise Make It Modular

### ISSUE THREAD

**Issue by jairofranchi** [workshopper/learnyounode#600]
This is the error that I'm getting when I run **learnyounode verify program.js** refering to exercise Make It Modular.

```
Additional module file handles callback argument

/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:188
    processors[i].call(self, mode, function (err, pass) {
                 ^

TypeError: Cannot read property 'call' of undefined
    at next (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:188:18)
    at /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:195:7
    at callback (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:26:15)
    at modFileError (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:31:5)
    at /home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:131:18
    at /home/ubuntu/workspace/mymodule.js:15:16
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by NJM8** [comment]
Can you post all your code?

**Comment by maxfong** [comment]
return callback(null, list)

**Comment by claudiocabral** [comment]
`return callback(null, list)` takes away the error but makes an invalid answer (the callback prints the array and not the elements of the array).

**Comment by AnshulMalik** [comment]
You should save the list of matching files in an array and then do `callback(null, list)`, outside the for loop.

**Comment by claudiocabral** [comment]
the following code passes all tests except the first one. Is there something I'm missing?
``` javascript
module.exports = function(dir, suffix, callback)
{
	var fs = require('fs');
	fs.readdir(dir, (err, files) => {
		if (err) return callback(err);
		var data = files.filter(file => file.endsWith("." + suffix));
		return (callback(null, data));
	});
}
```
```
                 ACTUAL                                 EXPECTED
   "[ 'CHANGELOG.md', 'LICENCE.md', 'README.md' ]" !=    "CHANGELOG.md"
   ""                                  !=    "LICENCE.md"
                                       !=    ""
```

**Comment by claudiocabral** [comment]
ops, just realised that I needed to update `program.js` too. The following passes all tests.
``` javascript
module = require("./module.js");
module(process.argv[2], process.argv[3], function(err, data) {
	if (err) return console.error(err);
	data.forEach(item => console.log(item));
});
```

**Comment by shanmukhateja** [comment]
This issue can be marked as closed as it has been resolved. Feel free to reopen the issue if you have something to contribute to it.
