### ISSUE TITLE
Got an Error after run `node learnyounode` 

### ISSUE THREAD

**Issue by VitozzRDX** [workshopper/learnyounode#627]
Got an Error after run `node learnyounode` 

E:\learnyounode-master>node learnyounode
module.js:549
    throw err;
    ^
Error: Cannot find module 'workshopper-adventure'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\learnyounode-master\learnyounode.js:1:84)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

My OS - Windows 7
Node version v8.11.3
npm version - 5.6.0

**Comment by VitozzRDX** [comment]
I've run `npm install` and now there is no any mistake 
But it just fail silently . Nothing happens when i run node node learnyounode
Still looking for an answer

**Comment by totuet** [comment]
Hi VitozzRDX, 
You shouldn't run 'node learnyounode', just simply 'learnyounode' and the course will run.

**Comment by shanmukhateja** [comment]
This issue can be closed as it seems to have been resolved.
