### ISSUE TITLE
Error installing on Mac

### ISSUE THREAD

**Issue by jackspaniel** [workshopper/learnyounode#629]
I tried cleaning the cache through npm and manually and I'm still seeing this:

```
macs-mbp-2:javascripting mac$ sudo npm install -g learnyounode
Password:
npm WARN deprecated colors-tmpl@1.0.0: no longer maintained
npm WARN deprecated boganipsum@0.1.0: no longer maintained
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/codeclimate/javascript-test-reporter.git /Users/mac/.npm/_cacache/tmp/git-clone-7db3edb9
npm ERR! /Users/mac/.npm/_cacache/tmp/git-clone-7db3edb9/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2018-08-02T19_53_09_020Z-debug.log
macs-mbp-2:javascripting mac$ learnyounode
-bash: learnyounode: command not found

```

**Comment by jackspaniel** [comment]
Here's the log:

```
182 silly resolveWithNewModule msee@0.3.5 checking installable status
183 silly fetchPackageMetaData error for codeclimate-test-reporter@github:codeclimate/javascript-test-reporter#97f1ff2cf18cd5f03191d3d53e671c47e954f2fa Command failed: /usr/bin/git clone -q git://github.com/codeclimate/javascript-test-reporter.git /Users/mac/.npm/_cacache/tmp/git-clone-139a2f02
183 silly fetchPackageMetaData /Users/mac/.npm/_cacache/tmp/git-clone-139a2f02/.git: Permission denied
184 verbose stack Error: Command failed: /usr/bin/git clone -q git://github.com/codeclimate/javascript-test-reporter.git /Users/mac/.npm/_cacache/tmp/git-clone-139a2f02
184 verbose stack /Users/mac/.npm/_cacache/tmp/git-clone-139a2f02/.git: Permission denied
184 verbose stack
184 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
184 verbose stack     at emitTwo (events.js:126:13)
184 verbose stack     at ChildProcess.emit (events.js:214:7)
184 verbose stack     at maybeClose (internal/child_process.js:925:16)
184 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
185 verbose cwd /Users/mac/lab/javascripting
186 verbose Darwin 15.6.0
187 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "learnyounode"
188 verbose node v8.11.3
189 verbose npm  v5.6.0
190 error code 1
191 error Command failed: /usr/bin/git clone -q git://github.com/codeclimate/javascript-test-reporter.git /Users/mac/.npm/_cacache/tmp/git-clone-139a2f02
191 error /Users/mac/.npm/_cacache/tmp/git-clone-139a2f02/.git: Permission denied
192 verbose exit [ 1, true ]
 ```

**Comment by AnshulMalik** [comment]
Hey @jackspaniel https://github.com/contentful/contentful.js/issues/211#issuecomment-349964501 might help

**Comment by jackspaniel** [comment]
Thanks - after some fits and starts I was able to make the problem go away by changing `/usr/local/lib/node_modules` to write access for everyone, then running `npm install -g learnyounode`without sudo. 

I guess I will be prepared if a student runs into the same issue!
