### ISSUE TITLE
Can't run learnyounode on macOS mojave

### ISSUE THREAD

**Issue by mersahin** [workshopper/learnyounode#650]
$ learnyounode
 
/Users/username/.npm-global/lib/node_modules/learnyounode/node_modules/workshopper-adventure/node_modules/commandico/node_modules/joi/lib/index.js:39
    return schema._init(...args);
                        ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/username/.npm-global/lib/node_modules/learnyounode/node_modules/workshopper-adventure/node_modules/commandico/node_modules/explicit/lib/validate/index.js:3:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
![image](https://user-images.githubusercontent.com/3853524/49233881-3ebf5b80-f3f7-11e8-85d0-a7986fcd8e51.png)

**Comment by fru123sa** [comment]
i'm getting this same error on ubuntu.

**Comment by mersahin** [comment]
@fru123sa 
i'm fixed;
i've a very old nodeJs
nodejs update,
solved.
